[package]
name = "asset-lint"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/zerocukor287/asset-lint"
# If I set up a "github pages" I should change this
homepage = "https://github.com/zerocukor287/asset-lint"
description = "CLI tool to find common problems with assets during game development"

[dependencies]
clap_derive = "4.6.3"
clap = { version = "4.6.3", features = ["derive"] }
log = "0.4.33"
env_logger = "0.11.11"
walkdir = "2.5.0"
blake3 = "1.8.5"
regex = "1.13.1"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
toml = "1.1.4"
serde-sarif = "0.8.0"
strum_macros = "0.28.0"
human_bytes = "0.4.3"