name: Release

# only on tags as "v1.2.3"
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"


permissions:
  contents: read

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # for taiki-e/create-gh-release-action
    steps:
      - uses: actions/checkout@v7
      - uses: taiki-e/create-gh-release-action@v1
        with:
          # (optional) Path to changelog.
          changelog: CHANGELOG.md

  upload-assets:
    needs: create-release
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          # no mac build yet
          #- target: x86_64-apple-darwin
          #  os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write # for taiki-e/upload-rust-binary-action
    steps:
      - uses: actions/checkout@v7
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          # (required) Binary names (non-extension portion of filename) to build and upload (whitespace or comma separated list).
          # Note that glob pattern is not supported yet.
          bin: asset-lint
          # (optional) Target triple, default is host triple.
          # This is optional but it is recommended that this always be set to
          # clarify which target you are building for if macOS is included in
          # the matrix because GitHub Actions changed the default architecture
          # of macos-latest since macos-14.
          target: ${{ matrix.target }}
